version: '3.8'
services:
  # Python web app service using the custom image
  web:
    image: pyweb  # Use the custom-built Python image
    build: .
    ports:
      - "5000:5000"  # Expose port 5000 on host machine
    environment:
      - DB_HOST=db
      - DB_NAME=testdb
      - DB_USER=user
      - DB_PASSWORD=password 
    depends_on:
      - db  # Ensure db starts before web, but it doesn't wait for db readiness
    entrypoint: /bin/sh -c "until nc -z -v -w60 db 5432; do echo 'Waiting for PostgreSQL...'; sleep 1; done; python app.py"  
  # PostgreSQL service
  db:
    image: postgres:13  # Use the official PostgreSQL image
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script
    ports:
      - "5432:5432"  # Expose port 5432 on host machine
volumes:
  postgres-data:
