apiVersion: v1
kind: Service
metadata:
  name: ClusterIp-svc
spec:
  selector:
    app: my_httpd_pod
  type: ClusterIP
  ports:
  - port: 80
---

## Command to be executed
# kubectl apply -f ClusterIp_creation.yml
# kubectl get svc
