apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: containter1
        image: httpd
        ports:
        - containerPort: 80

### Commands to be executed:
# kubectl apply -f loadbalancer_creation.yml
# kubectl get svc
# kubectl get deployment
# kubectl get replicaset
# kubectl get pods 
