apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: dev
spec:
  containers:
    - name: apache-web
      image: httpd
      ports:
        - containerPort: 80
    - name: Jenkins-ci
      image: jenkins
      ports:
        - containerPort: 8080

### Detailed command that get executed:

# kubectl get pods -n default               // It will display the pods which are running in default namespace
# kubectl get pods -o wide                 // It will display the pod that is running on which worker nodes
# kubectl apply -f multi_pod_creation.yml // It will just create pod using manifestfile
# kubectl get pods -n dev -o wide        // It will display the pod details running on DEV namespace

# This method called declarative way and another method is called Imperative way.
