apiVersion: v1
kind: Service
metadata:
  name: my-np-svc
spec:
  type: NodePort
  selector:
    app: my_httpd_pod
  ports:
  - port: 90
    targetPort: 80
    nodeport: 32001 
---

## Commands to be executed

# kubectl get services
# kubectl get svc
# kubectl apply -f nodeport_creation.yml 
# kubectl get svc
