apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
type: Opaque
data:
  username: YWRtaW4K
  password: bG9naW4xLTIK
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: myapp-secret
spec:
  containers:
  - name: myapp-secret
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
    - secretRef:
        name: dev-secret
---

## Please note, in order to encode/decode in linux use the following commands,

# ENCODING:-
# echo "username" | base64
# ans: dXNlcm5hbWUK
# echo "password" | base64
# ans: cGFzc3dvcmQK

# DECODING:-
# echo "dXNlcm5hbWUK" | base64 --decode
# ans: username
# echo "cGFzc3dvcmQK" | base64 --decode
# ans: password

### Commands to be executed inorder to provision configmap with pods:-
# kubectl apply -f secrets_with_pod.yml              // To create configmap with pod using manifest file
# kubectl get secrets                               // To list out the secrets
# kubectl get pods                                 // To list out the pods details
# kubectl exec -it secret-pod -- printenv         // To check the environment variables that we set it via secret to the containers. 
# kubectl exec -it secret-pod -- /bin/bash       // To get into the container. IN container, you type printenv, it will show the decoded secrets.
