version: '3.7'
services:
  apache:
    image: httpd:latest  # Use the Apache HTTP server image from Docker Hub
    ports:
      - "8080:80"  # Map port 8080 on your host to port 80 on the container
    volumes:
      - ./html:/usr/local/apache2/htdocs:ro  # Mount your custom HTML files from the local 'html' folder
    restart: unless-stopped  # Restart the container unless stopped manually
